version: '2'
services:
  app:
    build: .
    container_name: oic_gather
    ports:
      - 3000:3000
    command: bundle exec puma
    volumes:
      - .:/home/oic_gather
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    tty: true
    stdin_open: true

volumes:
  mysql-data:
