version: '3'
services:
  app:
    build: .
    container_name: "gather_gram_server"
    ports:
      - "3000:3000"
    command: bundle exec puma
    volumes:
      - .:/home/GatherGram
    depends_on:
      - db
    tty: true
    stdin_open: true

  front:
    build: ./frontend/.
    container_name: "gather_gram_front"
    ports:
      - "8080:8080"
    command: yarn start
    volumes:
      - ./frontend:/home/GatherGram/frontend

  db:
    image: mysql:5.7
    container_name: "mysql"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
