version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: "gather_gram_server"
    ports:
      - "3000:3000"
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/home/GatherGram
    depends_on:
      - db
    tty: true
    stdin_open: true

  front:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: "gather_gram_front"
    ports:
      - "8080:8080"
    command: yarn dev
    volumes:
      - ./frontend:/home/GatherGram/frontend

  db:
    image: mysql:5.7
    container_name: "mysql"
    ports:
      - "1205:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: "nginx"
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./public:/home/GatherGram/public

volumes:
  mysql-data:
