version: '3'
services:
  app:
    build: .
    container_name: "oic_gather"
    ports:
      - "3000:3000"
    command: bundle exec puma
    volumes:
      - .:/home/oic_gather
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: "mysql"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_PASSWORD: "gather"

volumes:
  mysql-data:
