default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
  host: db

development:
  <<: *default
  database: gather_gram_development

test:
  <<: *default
  database: gather_gram_test

production:
  <<: *default
  database: gather_gram_production
  password: <%= ENV['GATHER_GRAM_DATABASE_PASSWORD'] %>
