default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
  host: db

development:
  <<: *default
  database: oic_gather_development

test:
  <<: *default
  database: oic_gather_test

production:
  <<: *default
  database: oic_gather_production
  password: <%= ENV['OIC_GATHER_DATABASE_PASSWORD'] %>
